### ISSUE TITLE
Opt-in to crawl: p.a3.pm

### ISSUE THREAD

**Issue by aveao** [brortao/fediverse.space#29]
Heyo. This is my single user instance, would be cool if it was crawled too.

**Comment by brortao** [comment]
on it! apologies for the delay -- the crawler had an issue with your instance, for some reason.

the issue was caused by a trailing slash: `https://p.a3.pm/api/v1/timelines/public?local=true&limit=100` works, but `https://p.a3.pm/api/v1/timelines/public?local=true&limit=100/` doesn't!

i haven't run into this problem on other pleroma instances, do you have a custom setup or similar?

**Comment by aveao** [comment]
Nope, can you try again now? I updated the instance to latest master.

**Comment by brortao** [comment]
weird! either way -- you're on there now :)
