### ISSUE TITLE
Opt-in for toot.xayah.net

### ISSUE THREAD

**Issue by myoKun345** [brortao/fediverse.space#31]
I'd like to have my instance toot.xayah.net crawled.

**Comment by brortao** [comment]
Sure thing! Could you write to @tao@sunbeam.city from https://toot.xayah.net/@glyph, just to verify that it's your instance?

I don't really have a formal process for verifying instance ownership other than looking at the GitHub account, and since yours is pretty bare I thought I'd better make sure. Hope you don't mind.

**Comment by brortao** [comment]
your instance will be on https://www.fediverse.space within the next hour!
